/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __IssueTag_hpp__
#define __IssueTag_hpp__

#include <string>


class IssueTag
{
    public:
        std::string name;

        int64_t    TimeStamp;

        std::string detail;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "IssueTag"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int IssueTag::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int IssueTag::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int IssueTag::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t IssueTag::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* IssueTag::getTypeName()
{
    return "IssueTag";
}

int IssueTag::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* name_cstr = (char*) this->name.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->TimeStamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* detail_cstr = (char*) this->detail.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &detail_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int IssueTag::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__name_len__ > maxlen - pos) return -1;
    this->name.assign(((const char*)buf) + offset + pos, __name_len__ - 1);
    pos += __name_len__;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->TimeStamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __detail_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__detail_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__detail_len__ > maxlen - pos) return -1;
    this->detail.assign(((const char*)buf) + offset + pos, __detail_len__ - 1);
    pos += __detail_len__;

    return pos;
}

int IssueTag::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->name.size() + 4 + 1;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += this->detail.size() + 4 + 1;
    return enc_size;
}

uint64_t IssueTag::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x7a260d859cd3cf28LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
